"""empty message

Revision ID: 121569fb5070
Revises: c5dc32175b99
Create Date: 2020-12-13 22:43:18.155978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121569fb5070'
down_revision = 'c5dc32175b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('anonymous', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'anonymous')
    # ### end Alembic commands ###
